# Project: 项目1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = XGNB.o
LINKOBJ  = XGNB.o
LIBS     = -L"D:/BIT/计算机科学与程序设计/Dev C++/install3/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32" -L"C:/WpdPack/Lib" -static-libgcc -L"C:/WpdPack/Lib" -L"D:/SoftWare/DEV/Dev-Cpp/MinGW64/lib" -L"D:/SoftWare/DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -L"D:/SoftWare/DEV/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32"  C:/WpdPack/Lib/Packet.lib C:/WpdPack/Lib/wpcap.lib "C:/Program Files (x86)/Microsoft SDKs/Windows/v7.0A/Lib/WS2_32.Lib" "D:/BIT/计算机科学与程序设计/Dev C++/install3/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib32/libwsock32.a" -m32
INCS     = -I"D:/BIT/计算机科学与程序设计/Dev C++/install3/Dev-Cpp/MinGW64/include" -I"D:/BIT/计算机科学与程序设计/Dev C++/install3/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/BIT/计算机科学与程序设计/Dev C++/install3/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/WpdPack/Include" -I"C:/WpdPack/Include"
CXXINCS  = -I"D:/BIT/计算机科学与程序设计/Dev C++/install3/Dev-Cpp/MinGW64/include" -I"D:/BIT/计算机科学与程序设计/Dev C++/install3/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/BIT/计算机科学与程序设计/Dev C++/install3/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/BIT/计算机科学与程序设计/Dev C++/install3/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++" -I"C:/WpdPack/Include" -I"C:/WpdPack/Include"
BIN      = BIT.exe
CXXFLAGS = $(CXXINCS) -m32
CFLAGS   = $(INCS) -m32
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

XGNB.o: XGNB.cpp
	$(CPP) -c XGNB.cpp -o XGNB.o $(CXXFLAGS)
